name: 'Köther.io'
description: Our adventures
meta_description: "Köther - Kod Öl Gather"

aboutPage: true

markdown: redcarpet
highlighter: pygments

paginate: 20
baseurl: /
domain_name: 'http://www.kother.io'
google_analytics: 'UA-16656646-4'
#disqus_shortname: 'your-disqus-shortname'

# Details for the RSS feed generator
url:            'http://www.kother.io'
author:         'Köther.io'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
